CREATE EXTERNAL TABLE test0 STORED AS PARQUET LOCATION './test/test0.parquet';
CREATE EXTERNAL TABLE test1 STORED AS PARQUET LOCATION './test/test1.parquet';
CREATE EXTERNAL TABLE test2 STORED AS PARQUET LOCATION './test/test2.parquet';
CREATE EXTERNAL TABLE test3 STORED AS PARQUET LOCATION './test/test3.parquet';
